AdminApp/urls.py
from django.urls import path
from AdminApp import views
app_name="TunelyAdmin"
urlpatterns = [
    path('Index/',views.Index,name="Index"),
    path('Dash/',views.Dash,name="Dash"),
    
    path('Genre_add/',views.Genre_add,name="Genre_add"),
    path('Language_add/',views.Language_add,name="Language_add"),
    path('Mood_Add/',views.Mood_Add,name="Mood_Add"),

    path('DelGenre/<int:genreid>', views.DelGenre, name="DelGenre"),
    path('DelLang/<int:langid>', views.DelLang, name="DelLang"),
    path('DelMood/<int:Mid>', views.DelMood, name="DelMood"),

    path('logout/', views.logout, name="logout"),


]

Tunely/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('TunelyAdmin/', include("AdminApp.urls")),
    path('Creator/', include("Creator.urls")),
    path('User/', include("User.urls")),
    path('', include("Guest.urls")),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from User import views
app_name="User"
urlpatterns = [
    path('Index/',views.Index,name="Index"),
    path('Home/',views.Home,name="Home"),
    path('SocialHome/',views.SocialHome,name="SocialHome"),
    path('Login/',views.Login,name="Login"),
    path('SignUp/',views.SignUp,name="SignUp"),
    path('UsrProfile/',views.UsrProfile,name="UsrProfile"),
    path('Usrlogout/',views.Usrlogout,name="Usrlogout"),
    path('EditPage/<int:usrid>',views.EditPage,name="EditPage"),
    path('UpdateProfile/<int:usrid>',views.UpdateProfile,name="UpdateProfile"),
    path('UsrChngPass/',views.UsrChngPass,name="UsrChngPass"),
    path('ViewAlbum/<int:Aid>',views.ViewAlbum,name="ViewAlbum"),
    path('ViewProfile/<int:Cid>',views.ViewProfile,name="ViewProfile"),
    path('Followcr/<int:Cid>',views.Followcr,name="Followcr"),
    path('Unfollwcr/<int:Cid>',views.Unfollwcr,name="Unfollwcr"),
    path('search/',views.search,name="search"),
    path('play_song/',views.play_song,name="play_song"),
    path('play_album/',views.play_album,name="play_album"),
    path('play_playlist/',views.play_playlist,name="play_playlist"),
    path('play_crplaylist/',views.play_crplaylist,name="play_crplaylist"),
    path('CreatePlaylist/', views.CreatePlaylist, name='CreatePlaylist'),
    path('AllPlaylist/', views.AllPlaylist, name='AllPlaylist'),
    path('ViewPlaylist/<int:Pid>', views.ViewPlaylist, name='ViewPlaylist'),
    path('PlaylistView/<int:Pid>', views.PlaylistView, name='PlaylistView'),
    path('UpdatePlaylist/<int:Pid>', views.UpdatePlaylist, name='UpdatePlaylist'),
    path('AddtoPlaylist/', views.AddtoPlaylist, name='AddtoPlaylist'),
    path('delete_from_usr_playlist/<int:playlist_id>/<int:music_id>/', views.delete_from_usr_playlist, name='delete_from_usr_playlist'),
    path('AboutUs/', views.AboutUs, name='AboutUs'),
    path('download_music/', views.download_music, name='download_music'),
    path('songs_by_language/<int:Lid>', views.songs_by_language, name='songs_by_language'),
    path('songs_by_genre/<int:Gid>', views.songs_by_genre, name='songs_by_genre'),

]

AdminApp/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    Genre_Name = models.CharField(max_length=50)
    Genre_Icons = models.ImageField(upload_to='Genre_Icons/', blank=True, null=True)

class Language(models.Model):
    Lang = models.CharField(max_length=50)
    Lang_Char = models.CharField(max_length=50,blank=True, null=True)

class MusicMood(models.Model):
    Mood = models.CharField(max_length=50)

class Admindata(models.Model):
    mail = models.EmailField(unique=True)
    Password = models.CharField(max_length = 150)
    

AdminApp/views.py
from django.shortcuts import render,redirect
from AdminApp.models import*
from django.contrib import messages


# Create your views here.
def Index(request):
    if 'Admnid' in request.session:
        return render(request,"AdminTemp/index.html")
    else:
        messages.warning(request, 'Access Denied: Please log in to view this page.')
        return redirect('User:Login')

def Dash(request):
    return render(request,"AdminTemp/dashboard.html")

def Genre_add(request):
    if 'Admnid' in request.session:
        Genre_Data=Genre.objects.all()
        if request.method=="POST":
            gname = request.POST.get('genre_name')
            gicon = request.FILES['genre_icon']
            Genre.objects.create(Genre_Name=gname,
                                Genre_Icons=gicon)
            return render(request,"AdminTemp/Genre_Add.html",{'Gdata':Genre_Data})
        else:
            return render(request,"AdminTemp/Genre_Add.html",{'Gdata':Genre_Data})
    else:
        messages.warning(request, 'Access Denied: Please log in to view this page.')
        return redirect('User:Login')

def DelGenre(request,genreid):
    data=Genre.objects.filter(id=genreid)
    data.delete()
    return redirect("TunelyAdmin:Genre_add")

def Language_add(request):
    if 'Admnid' in request.session:
        ldata = Language.objects.all()
        if request.method=="POST":
            lang = request.POST.get('lang')
            char = request.POST.get('langchar')
            Language.objects.create(Lang=lang,Lang_Char=char)
            return render(request,"AdminTemp/Language_Add.html",{'Langdata':ldata})
        else:
            return render(request,"AdminTemp/Language_Add.html",{'Langdata':ldata})
    else:
        messages.warning(request, 'Access Denied: Please log in to view this page.')
        return redirect('User:Login')

def DelLang(request,langid):
    lang=Language.objects.filter(id=langid)
    lang.delete()
    return redirect("TunelyAdmin:Language_add")

def Mood_Add(request):
    if 'Admnid' in request.session:
        Mdata = MusicMood.objects.all()
        if request.method == "POST":
            mood = request.POST.get('mood')
            MusicMood.objects.create(Mood=mood)
            return render(request, "AdminTemp/mood_add.html",{'data':Mdata})
        else:
            return render(request,"AdminTemp/mood_add.html",{'data':Mdata})
    else:
        messages.warning(request, 'Access Denied: Please log in to view this page.')
        return redirect('User:Login')

def DelMood(request,Mid):
    mood=MusicMood.objects.filter(id=Mid)
    mood.delete()
    return redirect("TunelyAdmin:Mood_Add")

def logout(request):
    if 'Admnid' in request.session:
        del request.session["Admnid"]
        messages.success(request, 'Logged Out, Successfully')
        return redirect("User:Login")
    else:
        messages.warning(request, 'Access Denied: Please log in to view this page.')
        return redirect('User:Login')

AdminApp/templates/AdminTemp/Genre_Add.html
{% extends 'AdminTemp/Index.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<style>
.bg_ground{
    background-image: linear-gradient(to bottom, #172337 20%, #243b55 40%, #2f4a69 60%);
    height: 100%;
    width: 100%;
}

.genre-box{
    background-color: rgb(45, 150, 255);
    width: 60vh;
    margin: 0 auto;
    text-align: center;
    margin-bottom:10vh;
    color: #ffffff;
    border-radius: 12px;
    box-shadow: 0 0 13px 6px rgba(0, 0, 0, 0.35); 

}

h3{
    padding:1rem;
}
.name-box{
    padding-bottom: 5px;
}
.name-box input[type="text"] {
    width: 280px;
    height: 40px; 
    padding: 15px; 
    border-radius: 8px;
    border: none;
}
.button_div{
    padding-top:1rem;
    padding-bottom:1.8rem;
    
}
.sub_btn{
    background-image: linear-gradient(to bottom, #1e3146, #2f4a69 );
    color: white;
    width:20vh;
    height: 30px;
    font-size: 16px;
    border:none;
    overflow: hidden;
    border-radius: 5px;
    transition: transform 0.3s;
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.35); 

}
.sub_btn:hover{
    cursor: pointer;
    color: #6ddf08;
    transform: scale(1.1); 
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.35); 



}
p{
    font-size:16px;
    padding-top:2px;
    color: white;
}

.button_outer:hover{
    cursor: pointer;
    transform: scale(1.1); 
     
}


.button_outer { margin-top:10px;  background-image: linear-gradient(to bottom, #1e3146 ,#30466d); border-radius:12px; text-align: center; height: 36px; width: 220px; display: inline-block; transition: .2s; position: relative; overflow: hidden;}
.btn_upload {padding: 5px; color: #ffffff; text-align: center; position: relative; display: inline-block; overflow: hidden; z-index: 3; white-space: nowrap; }
.btn_upload input {position: absolute; width: 100%; left: 0; top: 0; width: 100%; height: 105%; cursor: pointer; opacity: 0; text-align:center;}
.file_uploading {width: 100%; height: 10px; margin-top: 20px; background: #ccc;}
.file_uploading .btn_upload {display: none;}
.processing_bar {position: absolute; left: 0; top: 0; width: 0; height: 100%; border-radius: 30px; background:#5db60f; transition: 3s; }
.file_uploading .processing_bar {width: 100%;}
.success_box {display: none; width: 50px; height: 50px; position: relative; border-radius: 30px;}
.success_box:before {content: ''; display: block; width: 9px; height: 18px; border-bottom: 5px solid #ffffff; border-right: 5px solid #ffffff; -webkit-transform:rotate(45deg); -moz-transform:rotate(45deg); -ms-transform:rotate(45deg); transform:rotate(45deg); position: absolute; left: 20px; top: 14px;}
.file_uploaded .success_box {display: inline-block;}
.file_uploaded {margin-top:10px; width: 50px; background:transparent; height: 50px;}


.card{
    box-shadow: 0 0 13px 8px rgba(0, 0, 0, 0.35); 
}

</style>

</head>
<body >

        <!-- Main-body start -->
        <div class="main-body bg_ground" >
            <div class="page-wrapper">
                <!-- Page-body start -->
                <div class="page-body">
                    <!-- Basic table card start -->
                    <div class="genre-box">
                        <h3>Add Genre</h3>
                        <form action="{% url 'TunelyAdmin:Genre_add' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="name-box">
                                <input type="text" name="genre_name"  placeholder="Genre Name" autocomplete="off" required="">
                            </div>

                            <div class="button_outer">
                                <div class="btn_upload">
                                    <input style="width: 100%; cursor: pointer;" type="file" id="upload_file" name="genre_icon" required="">
                                    <p>Add Icon</p>
                                </div>
                                <div class="processing_bar"></div>
                                <div class="success_box"></div>
                            </div>

                            <div class="button_div">
                                <button class="sub_btn" type="submit">Submit</button>
                            </div>
                        </form>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <h5>Genre Table</h5>
                            <div class="card-header-right">
                                <ul class="list-unstyled card-option">
                                    <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                    <li><i class="fa fa-window-maximize full-card"></i></li>
                                    <li><i class="fa fa-minus minimize-card"></i></li>
                                    <li><i class="fa fa-refresh reload-card"></i></li>
                                    <li><i class="fa fa-trash close-card"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-block table-border-style">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Genre Names</th>
                                            <th>Icons</th>
                                            <th style="width: 30%;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       {% for i in Gdata %} 
                                        <tr>
                                            <th scope="row"style="padding-top: 50px;">{{forloop.counter}}</th>
                                            <td style="padding-top: 50px;">{{i.Genre_Name}}</td>
                                            <td cellpadding="5" >
                                                <div>
                                                    <img class="img-fluid" src="{{i.Genre_Icons.url}}" style="width: 100px; height: 100px; object-fit: cover; border-radius: 8px; box-shadow: 0 0 13px 2px rgba(0, 0, 0, 0.28);  " alt="image">
                                                </div>
                                              </td>
                                              <td style="padding-top: 50px;">
                                                <div class="button-container">
                                                    <form action="{% url 'TunelyAdmin:DelGenre' i.id %}" style="display: inline;">
                                                        <button type="submit" class="btn waves-effect waves-light btn-grd-danger"><i class="ti-trash"></i>Delete</button>
                                                    </form>
                                                    <button type="submit" class="btn waves-effect waves-light btn-grd-inverse"><i class="ti-marker-alt"></i>Edit</button>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    
                    
      
                </div>
            </div>
        </div>
    </div>


</body>
<script>

    const btnUpload = document.getElementById("upload_file");
    const btnOuter = document.querySelector(".button_outer");

    btnUpload.addEventListener("change", function(e) {
        const ext = btnUpload.value.split('.').pop().toLowerCase();
        if (['gif', 'png', 'jpg', 'jpeg'].indexOf(ext) !== -1) {
            btnOuter.classList.add("file_uploading");

            // Simulate a delay to show the uploading progress
            setTimeout(function() {
                btnOuter.classList.add("file_uploaded");
            }, 2800);
        }
    });

</script>
</html>
{% endblock content %}

AdminApp/templates/AdminTemp/Language_Add.html
{% extends 'AdminTemp/Index.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<style>
.bg_ground{
    background-image: linear-gradient(to bottom, #172337 20%, #243b55 40%, #2f4a69 60%);
    height: 100%;
    width: 100%;
}

.genre-box{
    background-color: rgb(45, 150, 255);
    width: 60vh;
    margin: 0 auto;
    text-align: center;
    margin-bottom:10vh;
    color: #ffffff;
    border-radius: 12px;
    box-shadow: 0 0 13px 6px rgba(0, 0, 0, 0.35); 

}

h3{
    padding:1rem;
}
.name-box{
    padding-bottom: 5px;
}
.name-box input[type="text"] {
    width: 280px;
    height: 40px; 
    padding: 15px; 
    border-radius: 8px;
    border: none;
}
.button_div{
    padding-top:1rem;
    padding-bottom:1.8rem;
    
}
.sub_btn{
    background-image: linear-gradient(to bottom, #1e3146, #2f4a69 );
    color: white;
    width:20vh;
    height: 30px;
    font-size: 16px;
    border:none;
    overflow: hidden;
    border-radius: 5px;
    transition: transform 0.3s;
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.35); 

}
.sub_btn:hover{
    cursor: pointer;
    color: #6ddf08;
    transform: scale(1.1); 
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.35); 



}
p{
    font-size:16px;
    padding-top:2px;
    color: white;
}

.button_outer:hover{
    cursor: pointer;
    transform: scale(1.1); 
     
}



.card{
    box-shadow: 0 0 13px 8px rgba(0, 0, 0, 0.35); 
}

</style>

</head>
<body >

        <!-- Main-body start -->
        <div class="main-body bg_ground" >
            <div class="page-wrapper">
                <!-- Page-body start -->
                <div class="page-body">
                    <!-- Basic table card start -->
                    <div class="genre-box">
                        <h3>Add Languages</h3>
                        <form action="{% url 'TunelyAdmin:Language_add' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="name-box">
                                <input type="text" name="lang" required="" placeholder="Language name in english.">
                            </div>
                            <div class="name-box">
                                <input type="text" name="langchar" required="" placeholder="Languages name in original text">
                            </div>

                            <div class="button_div">
                                <button class="sub_btn" type="submit">Submit</button>
                            </div>

                        </form>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <h5>Genre Table</h5>
                            <div class="card-header-right">
                                <ul class="list-unstyled card-option">
                                    <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                    <li><i class="fa fa-window-maximize full-card"></i></li>
                                    <li><i class="fa fa-minus minimize-card"></i></li>
                                    <li><i class="fa fa-refresh reload-card"></i></li>
                                    <li><i class="fa fa-trash close-card"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-block table-border-style">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width:10%;">#</th>
                                            <th style="width:60%;">Languages</th>
                                            <th style="width:60%;">Character</th>
                                            <th style="width:30%;" >Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       {% for i in Langdata %} 
                                        <tr>
                                            <th scope="row">{{forloop.counter}}</th>
                                            <td>{{i.Lang}}</td>
                                            <td>{{i.Lang_Char}}</td>
                                            <td>
                                                <div class="button-container">
                                                    <form action="{% url 'TunelyAdmin:DelLang' i.id %}" style="display: inline;">
                                                        <button type="submit" class="btn waves-effect waves-light btn-grd-danger "><i class="ti-trash"></i>Delete </button>
                                                    </form>
                                                    <button type="submit" class="btn waves-effect waves-light btn-grd-inverse"><i class="ti-marker-alt"></i>Edit</button>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                    
                    
      
                </div>
            </div>
        </div>
    </div>


</body>
<script>

    const btnUpload = document.getElementById("upload_file");
    const btnOuter = document.querySelector(".button_outer");

    btnUpload.addEventListener("change", function(e) {
        const ext = btnUpload.value.split('.').pop().toLowerCase();
        if (['gif', 'png', 'jpg', 'jpeg'].indexOf(ext) !== -1) {
            btnOuter.classList.add("file_uploading");

            // Simulate a delay to show the uploading progress
            setTimeout(function() {
                btnOuter.classList.add("file_uploaded");
            }, 2800);
        }
    });

</script>
</html>
{% endblock content %}

AdminApp/templates/AdminTemp/mood_add.html
{% extends 'AdminTemp/Index.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<style>
.bg_ground{
    background-image: linear-gradient(to bottom, #172337 20%, #243b55 40%, #2f4a69 60%);
    height: 100%;
    width: 100%;
}

.genre-box{
    background-color: rgb(45, 150, 255);
    width: 60vh;
    margin: 0 auto;
    text-align: center;
    margin-bottom:10vh;
    color: #ffffff;
    border-radius: 12px;
    box-shadow: 0 0 13px 6px rgba(0, 0, 0, 0.35); 

}

h3{
    padding:1rem;
}
.name-box{
    padding-bottom: 5px;
}
.name-box input[type="text"] {
    width: 280px;
    height: 40px; 
    padding: 15px; 
    border-radius: 8px;
    border: none;
}
.button_div{
    padding-top:1rem;
    padding-bottom:1.8rem;
    
}
.sub_btn{
    background-image: linear-gradient(to bottom, #1e3146, #2f4a69 );
    color: white;
    width:20vh;
    height: 30px;
    font-size: 16px;
    border:none;
    overflow: hidden;
    border-radius: 5px;
    transition: transform 0.3s;
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.35); 

}
.sub_btn:hover{
    cursor: pointer;
    color: #6ddf08;
    transform: scale(1.1); 
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.35); 



}
p{
    font-size:16px;
    padding-top:2px;
    color: white;
}

.button_outer:hover{
    cursor: pointer;
    transform: scale(1.1); 
     
}



.card{
    box-shadow: 0 0 13px 8px rgba(0, 0, 0, 0.35); 
}

</style>

</head>
<body >

        <div class="main-body bg_ground" >
            <div class="page-wrapper">
                <div class="page-body">
                    <div class="genre-box">
                        <h3>Mood / Emotions</h3>
                        <form action="{% url 'TunelyAdmin:Mood_Add' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="name-box">
                                <input type="text" name="mood" required="" placeholder="Mood / Emotions">
                            </div>

                            <div class="button_div">
                                <button class="sub_btn" type="submit">Submit</button>
                            </div>

                        </form>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <h5>Mood / Emotions </h5>
                            <div class="card-header-right">
                                <ul class="list-unstyled card-option">
                                    <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                    <li><i class="fa fa-window-maximize full-card"></i></li>
                                    <li><i class="fa fa-minus minimize-card"></i></li>
                                    <li><i class="fa fa-refresh reload-card"></i></li>
                                    <li><i class="fa fa-trash close-card"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-block table-border-style">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width:10%;">#</th>
                                            <th style="width:60%;">Moods / Emotions</th>
                                            <th style="width:30%;" >Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       {% for i in data reversed %} 
                                        <tr>
                                            <th scope="row">{{forloop.counter}}</th>
                                            <td>{{i.Mood}}</td>
                                            <td>
                                                <div class="button-container">
                                                    <form action="{% url 'TunelyAdmin:DelMood' i.id %}" style="display: inline;">
                                                        <button type="submit" class="btn waves-effect waves-light btn-grd-danger "><i class="ti-trash"></i>Delete </button>
                                                    </form>
                                                    <button type="submit" class="btn waves-effect waves-light btn-grd-inverse"><i class="ti-marker-alt"></i>Edit</button>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                    
                    
      
                </div>
            </div>
        </div>
    </div>


</body>
<script>

    const btnUpload = document.getElementById("upload_file");
    const btnOuter = document.querySelector(".button_outer");

    btnUpload.addEventListener("change", function(e) {
        const ext = btnUpload.value.split('.').pop().toLowerCase();
        if (['gif', 'png', 'jpg', 'jpeg'].indexOf(ext) !== -1) {
            btnOuter.classList.add("file_uploading");

            // Simulate a delay to show the uploading progress
            setTimeout(function() {
                btnOuter.classList.add("file_uploaded");
            }, 2800);
        }
    });

</script>
</html>
{% endblock content %}