Guest/urls.py
from django.urls import path
from Guest import views
app_name="Guest"
urlpatterns = [
    path('',views.Login,name="Login"),
]

Tunely/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('TunelyAdmin/', include("AdminApp.urls")),
    path('Creator/', include("Creator.urls")),
    path('User/', include("User.urls")),
    path('', include("Guest.urls")),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from User import views
app_name="User"
urlpatterns = [
    path('Index/',views.Index,name="Index"),
    path('Home/',views.Home,name="Home"),
    path('SocialHome/',views.SocialHome,name="SocialHome"),
    path('Login/',views.Login,name="Login"),
    path('SignUp/',views.SignUp,name="SignUp"),
    path('UsrProfile/',views.UsrProfile,name="UsrProfile"),
    path('Usrlogout/',views.Usrlogout,name="Usrlogout"),
    path('EditPage/<int:usrid>',views.EditPage,name="EditPage"),
    path('UpdateProfile/<int:usrid>',views.UpdateProfile,name="UpdateProfile"),
    path('UsrChngPass/',views.UsrChngPass,name="UsrChngPass"),
    path('ViewAlbum/<int:Aid>',views.ViewAlbum,name="ViewAlbum"),
    path('ViewProfile/<int:Cid>',views.ViewProfile,name="ViewProfile"),
    path('Followcr/<int:Cid>',views.Followcr,name="Followcr"),
    path('Unfollwcr/<int:Cid>',views.Unfollwcr,name="Unfollwcr"),
    path('search/',views.search,name="search"),
    path('play_song/',views.play_song,name="play_song"),
    path('play_album/',views.play_album,name="play_album"),
    path('play_playlist/',views.play_playlist,name="play_playlist"),
    path('play_crplaylist/',views.play_crplaylist,name="play_crplaylist"),
    path('CreatePlaylist/', views.CreatePlaylist, name='CreatePlaylist'),
    path('AllPlaylist/', views.AllPlaylist, name='AllPlaylist'),
    path('ViewPlaylist/<int:Pid>', views.ViewPlaylist, name='ViewPlaylist'),
    path('PlaylistView/<int:Pid>', views.PlaylistView, name='PlaylistView'),
    path('UpdatePlaylist/<int:Pid>', views.UpdatePlaylist, name='UpdatePlaylist'),
    path('AddtoPlaylist/', views.AddtoPlaylist, name='AddtoPlaylist'),
    path('delete_from_usr_playlist/<int:playlist_id>/<int:music_id>/', views.delete_from_usr_playlist, name='delete_from_usr_playlist'),
    path('AboutUs/', views.AboutUs, name='AboutUs'),
    path('download_music/', views.download_music, name='download_music'),
    path('songs_by_language/<int:Lid>', views.songs_by_language, name='songs_by_language'),
    path('songs_by_genre/<int:Gid>', views.songs_by_genre, name='songs_by_genre'),

]

Guest/models.py
from django.db import models

# Create your models here.

Guest/views.py
from django.shortcuts import render

# Create your views here.
def Login(request):
    return render(request,"GuestTemp/Login.html")

Guest/templates/GuestTemp/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tunely</title>
    <link rel="icon" href="{% static 'UsrAssets/img/favicon.ico' %}" type="image/x-icon">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@700&family=Merienda:wght@800&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'UsrAssets/css/forms-dow.css' %}">
</head>
<body>
    <div class="login-box">
        <div class="logo-text">
          <h2>Tunely</h2>
        </div>
        <form method="POST" action="{% url 'User:Login'%}" enctype="multipart/form-data">
        {% csrf_token %}
          <div class="user-box">
            <input type="email" name="mail" autocomplete="off" required="">
            <label>Email</label>
          </div>
          <div class="user-box">
            <input type="password" name="pass" autocomplete="off" required="">
            <label>Password</label>
          </div>
          {% if ERR %}
            <div class="err-msg"><i class="bi bi-exclamation-triangle"> </i>{{ ERR }}</div>
          {% endif %}
          <div class="login-links">
            <span class="link-2"><a href="#">Forgot Password</a></span>
            <span class="link-1"><a href="{% url 'User:SignUp'%}">Sign-Up</a></span>
          </div>
          <div class="submit-btn">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <button type="submit">Log-In</button>
          </div>
        </form>
        <div class="split-div">
          <svg class="svg1">
            <line x1="1" y1="10" x2="100%" y2="10" style="stroke:rgb(255, 255, 255);stroke-width:1" />
          </svg>
          <p>OR</p>
          <svg class="svg2">
            <line x1="1" y1="10" x2="100%" y2="10" style="stroke:rgb(255, 255, 255);stroke-width:1" />
          </svg>
        </div>
          
          <div class="google-signin">
            <a href=""><img src="{% static 'UsrAssets/icon/google.png' %}" alt="" srcset=""></a>
            <button><a href=""> Continue With Google</a></button>
          </div>
    </div>  
    
      <div class="popup-message" id="popup-message" >
          <div class="popup-content">
              <div class="success-animation">
                <svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52">
                  <circle class="checkmark__circle" cx="26" cy="26" r="25" fill="none" />
                  <path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
                </svg>
              </div>
              <p id="popup-text"></p>
          </div>
      </div>

      <div class="warning-message" id="warning-message" >
        <div class="popup-content">
          <div class="f-modal-alert">
            <div class="f-modal-icon f-modal-warning scaleWarning">
                <span class="f-modal-body pulseWarningIns"></span>
                <span class="f-modal-dot pulseWarningIns"></span>
            </div>
          </div>
            <p id="popup-text-warn"></p>
        </div>
      </div>
    
      <div class="login-overlay" id="overlaylog"></div>


</body>
</html>