Creator/urls.py
from django.urls import path
from Creator import views
app_name="Creator"
urlpatterns = [
    path('CrIndex/',views.CrIndex,name="CrIndex"),
    path('CrHome/',views.CrHome,name="CrHome"),
    path('SignUp/',views.SignUp,name="SignUp"),
    path('logout/',views.logout,name="logout"),
    path('CrProfile/',views.CrProfile,name="CrProfile"),
    path('CrEditPage/<int:Cid>',views.CrEditPage,name="CrEditPage"),
    path('UpdateProfile/<int:Cid>',views.UpdateProfile,name="UpdateProfile"),
    path('CrchngPass/',views.CrchngPass,name="CrchngPass"),
    path('CrUploads/',views.CrUploads,name="CrUploads"),
    path('MusicUpload/', views.MusicUpload, name="MusicUpload"),
    path('EditMusic/<int:Mid>',views.EditMusic,name="EditMusic"),
    path('UpdateMusic/<int:Mid>',views.UpdateMusic,name="UpdateMusic"),
    path('delete_music/<int:Mid>',views.delete_music,name="delete_music"),
    path('CrAlbums/',views.CrAlbums,name="CrAlbums"),
    path('AlbumView/<int:Aid>',views.AlbumView,name="AlbumView"),
    path('ViewAlbum/<int:Aid>',views.ViewAlbum,name="ViewAlbum"),
    path('UpdateAlbum/<int:Aid>',views.UpdateAlbum,name="UpdateAlbum"),
    path('deleteAlbum/<int:Aid>',views.deleteAlbum,name="deleteAlbum"),
    path('search/',views.search,name="search"),
    path('play_song/',views.play_song,name="play_song"),
    path('play_album/',views.play_album,name="play_album"),
    path('play_playlist/',views.play_playlist,name="play_playlist"),
    path('ViewProfile/<int:Cid>',views.ViewProfile,name="ViewProfile"),
    path('Followfn/<int:Cid>',views.Followfn,name="Followfn"),
    path('Unfollow/<int:Cid>/', views.Unfollow, name="Unfollow"),
    path('CreatorPlaylist/', views.CreatorPlaylist, name="CreatorPlaylist"),
    path('AllCrPlaylist/', views.AllCrPlaylist, name="AllCrPlaylist"),
    path('PlaylistView/<int:Pid>/', views.PlaylistView, name="PlaylistView"),
    path('ViewCrPlaylist/<int:Pid>/', views.ViewCrPlaylist, name="ViewCrPlaylist"),
    path('deleteCrplaylist/<int:Pid>/', views.deleteCrplaylist, name="deleteCrplaylist"),
    path('UpdateCrplaylist/<int:Pid>',views.UpdateCrplaylist,name="UpdateCrplaylist"),
    path('get_playlist_status/<int:playlist_id>/', views.get_playlist_status, name='get_playlist_status'),
    path('update_playlist_status/<int:playlist_id>/', views.update_playlist_status, name='update_playlist_status'),
    path('AddtoCrPlaylist/', views.AddtoCrPlaylist, name='AddtoCrPlaylist'),
    path('delete_from_playlist/<int:playlist_id>/<int:music_id>/', views.delete_from_playlist, name='delete_from_playlist'),
    path('delnotification/<int:Nid>/', views.delnotification, name='delnotification'),
    path('songs_by_language/<int:Lid>/', views.songs_by_language, name='songs_by_language'),
    path('songs_by_genre/<int:Gid>/', views.songs_by_genre, name='songs_by_genre'),
]

Tunely/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('TunelyAdmin/', include("AdminApp.urls")),
    path('Creator/', include("Creator.urls")),
    path('User/', include("User.urls")),
    path('', include("Guest.urls")),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from User import views
app_name="User"
urlpatterns = [
    path('Index/',views.Index,name="Index"),
    path('Home/',views.Home,name="Home"),
    path('SocialHome/',views.SocialHome,name="SocialHome"),
    path('Login/',views.Login,name="Login"),
    path('SignUp/',views.SignUp,name="SignUp"),
    path('UsrProfile/',views.UsrProfile,name="UsrProfile"),
    path('Usrlogout/',views.Usrlogout,name="Usrlogout"),
    path('EditPage/<int:usrid>',views.EditPage,name="EditPage"),
    path('UpdateProfile/<int:usrid>',views.UpdateProfile,name="UpdateProfile"),
    path('UsrChngPass/',views.UsrChngPass,name="UsrChngPass"),
    path('ViewAlbum/<int:Aid>',views.ViewAlbum,name="ViewAlbum"),
    path('ViewProfile/<int:Cid>',views.ViewProfile,name="ViewProfile"),
    path('Followcr/<int:Cid>',views.Followcr,name="Followcr"),
    path('Unfollwcr/<int:Cid>',views.Unfollwcr,name="Unfollwcr"),
    path('search/',views.search,name="search"),
    path('play_song/',views.play_song,name="play_song"),
    path('play_album/',views.play_album,name="play_album"),
    path('play_playlist/',views.play_playlist,name="play_playlist"),
    path('play_crplaylist/',views.play_crplaylist,name="play_crplaylist"),
    path('CreatePlaylist/', views.CreatePlaylist, name='CreatePlaylist'),
    path('AllPlaylist/', views.AllPlaylist, name='AllPlaylist'),
    path('ViewPlaylist/<int:Pid>', views.ViewPlaylist, name='ViewPlaylist'),
    path('PlaylistView/<int:Pid>', views.PlaylistView, name='PlaylistView'),
    path('UpdatePlaylist/<int:Pid>', views.UpdatePlaylist, name='UpdatePlaylist'),
    path('AddtoPlaylist/', views.AddtoPlaylist, name='AddtoPlaylist'),
    path('delete_from_usr_playlist/<int:playlist_id>/<int:music_id>/', views.delete_from_usr_playlist, name='delete_from_usr_playlist'),
    path('AboutUs/', views.AboutUs, name='AboutUs'),
    path('download_music/', views.download_music, name='download_music'),
    path('songs_by_language/<int:Lid>', views.songs_by_language, name='songs_by_language'),
    path('songs_by_genre/<int:Gid>', views.songs_by_genre, name='songs_by_genre'),

]

User/models.py
from django.db import models
from Creator.models import*

# Create your models here.


class FormUser(models.Model):
    name = models.CharField(max_length=50)
    usr_name = models.CharField(max_length=50,null=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=50)
    picture = models.ImageField(upload_to="UserPictures/Profile",null=True, blank=True)
    bannerimage = models.ImageField(upload_to="UserPictures/Banner",null=True,blank=True)
    date_joined = models.DateTimeField(auto_now_add=True,null=True)

class Playlist(models.Model):
    PlaylistName = models.CharField(max_length=50)
    Playlist_Cover = models.ImageField(upload_to="User/Playlist", null=True, blank=True)
    UsrId = models.ForeignKey(FormUser, on_delete=models.CASCADE)

class PlaylistItem(models.Model):
    Plid = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    MusicId = models.ForeignKey(Music, on_delete=models.CASCADE)

class FollowCr(models.Model):
    follower = models.ForeignKey(FormUser, on_delete=models.CASCADE, related_name='following_User')
    following = models.ForeignKey(Creators, on_delete=models.CASCADE, related_name='followed_Creator')
    date_followed = models.DateTimeField(auto_now_add=True)

User/views.py
from django.shortcuts import render,redirect
from Creator.models import Creators
from User.models import *
from Creator.models import *
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.utils.datastructures import MultiValueDictKeyError
from fuzzywuzzy import fuzz
from django.shortcuts import get_object_or_404
import random 
from random import randint
from django.http import JsonResponse
from datetime import date
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
import os


# Create your views here.


def Index(request):
    pldata = playlist_data(request)
    messages_to_display = messages.get_messages(request)
    return render(request,"UserTemp/User_Index.html",{'pldata':pldata,'messages_to_display':messages_to_display})

def playlist_data(request):
    user_id = request.session.get('Usrid')
    if user_id:
        user = FormUser.objects.get(id=user_id)
        if user:
            playlist_data = Playlist.objects.filter(UsrId=user)
            return list(playlist_data)
        
def generate_random_color(last_color=None):
    color_palette = [ "#008600","#374ca9","#c9b8ab", "#ff7300", "#ff0059", "#a600ff","#b2702d", "#00ac7e","#dfab01","#7300ff"]
    available_colors = [color for color in color_palette if color != last_color]
    random_color = available_colors[randint(0, len(available_colors) - 1)]
    return random_color

def Home(request):
    if 'Usrid' in request.session:
        pldata = playlist_data(request)
        user_id = request.session['Usrid']
        langdata = Language.objects.all().order_by('?')[:6]
        gdata = Genre.objects.all().order_by('?')[:6]
        albums_data = Albums.objects.all().order_by('?')[:6]
        following_creators = Creators.objects.filter(followed_Creator__follower_id=user_id)
        if following_creators.exists():
            music_data = Music.objects.filter(Q(CrId__in=following_creators) | Q(collaborator_1__in=following_creators) | Q(collaborator_2__in=following_creators) | Q(collaborator_3__in=following_creators)).order_by('?')[:6]
        else:
            music_data = Music.objects.all().order_by('?')[:6]
        current_date = date.today()
        latest_releases = Music.objects.filter(release_date__lt=current_date).order_by('-release_date')[:6]
        last_color = None
        color_list = []
        for item in langdata:
            color = generate_random_color(last_color)
            color_list.append(color)
            last_color = color
        messages_to_display = messages.get_messages(request)
        return render(request, "UserTemp/Homepage.html", {'pldata': pldata,
                                                        'Ldata': zip(langdata, color_list),
                                                        'Gdata':gdata,
                                                        'albums_data':albums_data,
                                                        'music_data':music_data,
                                                        'latest_releases':latest_releases,
                                                        'messages_to_display':messages_to_display,
                                                        })
    else:
        messages.warning(request, 'Access Denied: Please log in to view this page.')
        return redirect('User:Login')


def SocialHome(request):
        pldata = playlist_data(request)
        # user_id = request.session['Usrid']
        langdata = Language.objects.all().order_by('?')[:6]
        gdata = Genre.objects.all().order_by('?')[:6]
        albums_data = Albums.objects.all().order_by('?')[:6]
        # following_creators = Creators.objects.filter(followed_Creator__follower_id=user_id)
        # if following_creators.exists():
        #     music_data = Music.objects.filter(Q(CrId__in=following_creators) | Q(collaborator_1__in=following_creators) | Q(collaborator_2__in=following_creators) | Q(collaborator_3__in=following_creators)).order_by('?')[:6]
        # else:
        #     music_data = Music.objects.all().order_by('?')[:6]
        current_date = date.today()
        latest_releases = Music.objects.filter(release_date__lt=current_date).order_by('-release_date')[:6]
        last_color = None
        color_list = []
        for item in langdata:
            color = generate_random_color(last_color)
            color_list.append(color)
            last_color = color
        messages_to_display = messages.get_messages(request)
        return render(request, "UserTemp/Homepage.html", {'pldata': pldata,
                                                        'Ldata': zip(langdata, color_list),
                                                        'Gdata':gdata,
                                                        'albums_data':albums_data,
                                                        # 'music_data':music_data,
                                                        'latest_releases':latest_releases,
                                                        'messages_to_display':messages_to_display,
                                                        })

def Login(request):
    if request.method == 'POST':
        Mail = request.POST.get('mail')
        Pass = request.POST.get('pass')
        Crlogin = Creators.objects.filter(Email=Mail,Password=Pass).count()
        Fm_User = FormUser.objects.filter(email=Mail,password=Pass).count()
        Tunely_Admin = Admindata.objects.filter(mail=Mail,Password=Pass).count()
        if Crlogin > 0:
            Cr = Creators.objects.get(Email=Mail,Password=Pass)
            request.session['Crid'] = Cr.id
            Crname = Cr.UsrName
            messages.success(request, 'Successfully Logged in as ' + Crname )
            return redirect("Creator:CrHome")
        elif Fm_User > 0:
            Usr = FormUser.objects.get(email=Mail,password=Pass)
            request.session['Usrid'] = Usr.id
            UsrName = Usr.name
            messages.success(request, 'Successfully Logged in as ' + UsrName )
            return redirect('User:Home')
        elif Tunely_Admin > 0:
            Admn = Admindata.objects.get(mail=Mail,Password=Pass)
            request.session['Admnid'] = Admn.id
            return redirect('TunelyAdmin:Index')
        else:
            error = "Invalid email or password !"
            return render(request,"UserTemp/Login.html",{'ERR':error})
    else:
        messages_to_display = messages.get_messages(request)
        return render(request,"UserTemp/Login.html", {'messages_to_display': messages_to_display})

def Usrlogout(request):
    if 'Usrid' in request.session:
        del request.session["Usrid"]
        messages.success(request, 'Logged Out, Successfully')
        return redirect("User:Login")
    else:
        return redirect('User:Login')
    
def SignUp(request):
    if request.method == "POST":
        name = request.POST.get('Name')
        email = request.POST.get('mail')
        password = request.POST.get('pass')
        if FormUser.objects.filter(email=email).exists():
            messages.warning(request, 'This Mail id is linked to an existing account. Please choose a different email or login to the existing account.')
            return redirect('User:SignUp')
        FormUser.objects.create(name=name, 
                                email=email, 
                                password=password)
        messages.success(request, 'Sign-Up successful, Please login to your account.')
        return redirect('User:Login')
    messages_to_display = messages.get_messages(request)
    return render(request, 'UserTemp/SignUp.html',{'messages_to_display':messages_to_display})

def UsrProfile(request):
    if 'Usrid' in request.session:
        usr = FormUser.objects.get(id=request.session['Usrid'])
        user = get_object_or_404(FormUser, id=usr.id)
        following_creators = FollowCr.objects.filter(follower=user)
        followed_creators_details = []
        for follow_relation in following_creators:
            followed_creator = follow_relation.following
            creator_details = {
                'id': followed_creator.id,
                'UsrName': followed_creator.UsrName,
                'Profile_Picture': followed_creator.Profile_Picture.url if followed_creator.Profile_Picture else None,
            }
            followed_creators_details.append(creator_details)
        pldata = playlist_data(request)
        return render(request, "UserTemp/UsrProfile.html",{'pldata':pldata,
                                                            'USR':usr,
                                                            'Following':followed_creators_details,
                                                            })
    else:
        messages.warning(request, 'Access Denied: Please log in to view this page.')
        return redirect('User:Login')

def EditPage(request,usrid):
    if 'Usrid' in request.session:
        usr = FormUser.objects.get(id=usrid)
        pldata = playlist_data(request)
        return render(request, "UserTemp/Editprofile.html",{'pldata':pldata,'USR':usr})
    else:
        messages.warning(request, 'Access Denied: Please log in to view this page.')
        return redirect('User:Login')

def UpdateProfile(request, usrid):
    if request.method == "POST":
        Unam = request.POST.get("usrname")
        name = request.POST.get("name")
        try:
            banner_img = request.FILES['banner-img']
            fs_banner = FileSystemStorage()
            banner_file = fs_banner.save(banner_img.name, banner_img)
        except MultiValueDictKeyError:
            banner_file = FormUser.objects.get(id=usrid).bannerimage
        try:
            profile_img = request.FILES['profile-img']
            fs_profile = FileSystemStorage()
            profile_file = fs_profile.save(profile_img.name, profile_img)
        except MultiValueDictKeyError:

User/templates/UserTemp/AllPlaylists.html
{% extends 'UserTemp/User_Index.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tunely</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cantora+One&family=Roboto:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'CrAssets/css/style.css ' %}"/>
    <script>
        var scrollPosition = sessionStorage.removeItem('scrollPosition');

        if (scrollPosition) {
            document.querySelector('.body-container').scrollTop = scrollPosition;
        }

        window.addEventListener('beforeunload', function () {
            sessionStorage.setItem('scrollPosition', document.querySelector('.body-container').scrollTop);
        });

        document.addEventListener("DOMContentLoaded", function () {
            var bodyContainer = document.querySelector('.body-container');
            bodyContainer.addEventListener('scroll', function () {
            
            });
        });
    </script>

</head>
<body>
    <div>

    </div>
    <div class="page-container-rel" >
        <div class="playlists-container" id="section1">
            <h4>All PlayLists</h4>
                <div class="item-container-add" onclick="addToPlaylistTrigger()">
                    <div class="items-card-add" >
                        <span><i class="bi bi-plus-lg"></i></span>
                    </div>
                    <h5>Create New</h5>
               </div>
            {% for i in Playlist %}
                <div class="item-container">
                    <a href="{% url 'User:ViewPlaylist' i.id %}">
                        <div class="items-card">
                            <div class="album-cover-playicon-container">
                                <div class="playlistcover-playicon" data-playlist-id="{{ i.id }}">                                              
                                    <span><i class="bi bi-play-fill"></i></span>
                                </div>
                            </div>
                            {% if i.Playlist_Cover %}
                                <img src="{{i.Playlist_Cover.url}}" alt="">
                            {% else %}
                                <img src="{% static 'Crassets/img/default playlist cover.jpg' %}" alt="" srcset="">
                            {% endif %}
                        </div>
                        <h5 class="{% if i.PlaylistName|length > 15 %}scrolling-text{% endif %}">{{i.PlaylistName}}</h5>
                    </a>
                </div>
            {% endfor %}    
        </div>
    </div>

    <div class="footer">
        <div class="footer-section">
            <h4>Tunely</h4>
            <ul>
                <li><a href="#">About</a></li>
                <li><a href="#">Origin</a></li>
            </ul>
        </div>
        
        <div class="footer-section">
            <h4>Community</h4>
            <ul>
                <li><a href="{% url 'Creator:SignUp' %}">For Artists</a></li>
                <li><a href="#">Advertising</a></li>
            </ul>
        </div>
        
        <div class="footer-section">
            <h4>Social</h4>
            <ul>
                <li><a href="#"> <i class="bi bi-envelope"></i> Mail</a></li>
                <li><a href="#"> <i class="bi bi-twitter-x"></i> Twitter</a></li>
                <li><a href="#"> <i class="bi bi-instagram"></i> Instagram</a></li>
            </ul>
        </div>
        
        <div class="footer-section">
            <h4>Useful Links</h4>
            <ul>
                <li><a href="#">Support</a></li>
                <li><a href="#">Terms of Use</a></li>
                <li><a href="#">Privacy Policy</a></li>
            </ul>
        </div>

        <div class="footer-line"></div>
        
        <div class="footer-copyright">
            <p>&copy; 2024 Tunely</p>
        </div>
    </div>
    


    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script> 
    <script src="{% static 'UsrAssets/js/playfromcover.js ' %}"></script> 

</body>
</html>
{% endblock content %}

User/templates/UserTemp/Homepage.html
{% extends 'UserTemp/User_Index.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tunely</title>
    <link rel="stylesheet" href="{% static 'CrAssets/css/style.css ' %}"/>

</head>
<body>
    <div class="target-buttons-home" id="targetbuttonid">
        <button onclick="scrollToSection('tophitssection')">Suggested </button>
        <button onclick="scrollToSection('genresection')">Genres</button>
        <button onclick="scrollToSection('albumssection')">Albums</button>
        <button onclick="scrollToSection('langsection')">Languages</button>
        <button onclick="scrollToSection('newreleasesect')">New releases</button>
    </div>


    <br>
            {% if music_data %}
                <div class="songs-section-home" id="tophitssection">
                    <h2>Suggested For You</h2>
                    <div class="home-songs-container">
                        <table>
                            {% for music in music_data %}
                                <tr>
                                    <td style="width: 8%;"><img src="{{ music.cover_art.url }}" alt=""></td>
                                    <td style="width: 15%;  overflow: hidden;">
                                        <div class="{% if music.Title|length > 17 %}table-title-div{% endif %}">{{ music.Title }}</div>
                                    </td>
                                    <td style="overflow:hidden;">
                                        <div class="{% if music.CrId.UsrName and music.collaborator_1.UsrName and music.collaborator_2.UsrName|length > 10 %}search-table-artists{% endif %}">
                                            <a href="{% url 'User:ViewProfile' music.CrId.id %}">{{ music.CrId.UsrName }}</a>
                                            {% if music.collaborator_1 %}{% with music.collaborator_1 as collab %}, <a href="{% url 'User:ViewProfile' collab.id %}">{{ collab.UsrName }}</a>{% endwith %}{% endif %} 
                                            {% if music.collaborator_2 %}{% with music.collaborator_2 as collab %}, <a href="{% url 'User:ViewProfile' collab.id %}">{{ collab.UsrName }}</a>{% endwith %}{% endif %}
                                            {% if music.collaborator_3 %}{% with music.collaborator_3 as collab %}, <a href="{% url 'User:ViewProfile' collab.id %}">{{ collab.UsrName }}</a>{% endwith %}{% endif %}
                                        </div>
                                    </td>
                                    <td style="width: 15%;  white-space: nowrap; text-align: center;">
                                        85603722  <i class="bi bi-suit-heart"></i>
                                    </td>
                                    <td style="width: 15%;">
                                        <div class="search-play-icon" style="margin-left: 40px;" data-song-id="{{ music.id }}">                                              
                                            <a href="#" class="play-music" >
                                            <span><i class="bi bi-play-fill"></i></span>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>     
                </div>   
            {% endif %}


    {% if Gdata %}
        <div class="albums-container-home" id="genresection">
            <h4>Play By Genre</h4>

            {% for i in Gdata %}
                <div class="item-container">
                    <a href="{% url 'User:songs_by_genre' i.id %}">
                        <div class="items-card">
                            <span class="{% if i.Genre_Name|length > 10 %}scrolling-text{% endif %}">{{ i.Genre_Name }}</span>
                            <img src="{{i.Genre_Icons.url}}" alt="">
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div> 
    {% endif %}

    {% if albums_data %}
        <div class="albums-section-home" id="albumssection">
            <h2>Play By Albums</h2>
            <div class="search-album-container">
                {% for album in albums_data %}
                    <div class="item-container">
                        <a href="{% url 'User:ViewAlbum' album.id %}">
                            <div class="items-card">
                                <div class="album-cover-playicon-container">
                                    <div class="albumcover-playicon" data-album-id="{{ album.id }}">                                              
                                        <span><i class="bi bi-play-fill"></i></span>
                                    </div>
                                </div>
                                <img src="{{ album.Album_Cover.url }}" alt="">
                            </div>
                            <h5 class="{% if album.Album_Name|length > 10 %}scrolling-text{% endif %}">{{album.Album_Name}}</h5>
                        </a>
                    </div>
                {% endfor %}
            </div>     
        </div>   
    {% endif %}

    <div class="albums-container-home" id="langsection">
        <h4>Play By Language</h4>
        <!-- <p><a href="#">view more</a></p> -->
        {% for item, color in Ldata %}
            <div class="item-container">
                <a href="{% url 'User:songs_by_language' item.id %}">
                    <div class="items-card" style="background-color: {{ color }};">
                        <div class="item-card-overlay">
                            <h4 class="{% if item.Lang_Char|length > 10 %}scrolling-text{% endif %}">{{ item.Lang_Char }}</h4>
                        </div>
                    </div>
                    <h5 class="{% if item.Lang|length > 10 %}scrolling-text{% endif %}">{{ item.Lang }}</h5>
                </a>
            </div>
        {% endfor %}
    </div>

    {% if latest_releases %}
                <div class="songs-section-home" id="newreleasesect">
                    <h2>New Releases</h2>
                    <div class="home-songs-container">
                        <table>
                            {% for music in latest_releases %}
                                <tr>
                                    <td style="width: 8%;"><img src="{{ music.cover_art.url }}" alt=""></td>
                                    <td style="width: 15%;  overflow: hidden;">
                                        <div class="{% if music.Title|length > 17 %}table-title-div{% endif %}">{{ music.Title }}</div>
                                    </td>
                                    <td style="overflow:hidden;">
                                        <div class="{% if music.CrId.UsrName and music.collaborator_1.UsrName and music.collaborator_2.UsrName and music.collaborator_3.UsrName|length > 10 %}search-table-artists{% endif %}">
                                            <a href="{% url 'User:ViewProfile' music.CrId.id %}">{{ music.CrId.UsrName }}</a>
                                            {% if music.collaborator_1 %}{% with music.collaborator_1 as collab %}, <a href="{% url 'User:ViewProfile' collab.id %}">{{ collab.UsrName }}</a>{% endwith %}{% endif %} 
                                            {% if music.collaborator_2 %}{% with music.collaborator_2 as collab %}, <a href="{% url 'User:ViewProfile' collab.id %}">{{ collab.UsrName }}</a>{% endwith %}{% endif %}
                                            {% if music.collaborator_3 %}{% with music.collaborator_3 as collab %}, <a href="{% url 'User:ViewProfile' collab.id %}">{{ collab.UsrName }}</a>{% endwith %}{% endif %}
                                        </div>
                                    </td>
                                    <td style="width: 15%;  white-space: nowrap; text-align: center;">
                                        85603722  <i class="bi bi-suit-heart"></i>
                                    </td>
                                    <td style="width: 15% ">
                                        <div class="search-play-icon"  style="margin-left: 40px;"  data-song-id="{{ music.id }}">                                              
                                            <a href="#" class="play-music" >
                                            <span><i class="bi bi-play-fill"></i></span>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>     
                </div>   
            {% endif %}

    <div class="footer">
        <div class="footer-section">
            <h4>Tunely</h4>
            <ul>
                <li><a href="{% url 'User:AboutUs' %}">About</a></li>
                <li><a href="#">Origin</a></li>
            </ul>
        </div>
        
        <div class="footer-section">
            <h4>Community</h4>
            <ul>
                <li><a href="{% url 'Creator:SignUp' %}">For Artists</a></li>
                <li><a href="#">Advertising</a></li>
            </ul>
        </div>
        
        <div class="footer-section">
            <h4>Social</h4>
            <ul>
                <li><a href="#"> <i class="bi bi-envelope"></i> Mail</a></li>
                <li><a href="#"> <i class="bi bi-twitter-x"></i> Twitter</a></li>
                <li><a href="#"> <i class="bi bi-instagram"></i> Instagram</a></li>
            </ul>
        </div>
        
        <div class="footer-section">
            <h4>Useful Links</h4>
            <ul>
                <li><a href="#">Support</a></li>
                <li><a href="#">Terms of Use</a></li>
                <li><a href="#">Privacy Policy</a></li>
            </ul>
        </div>

        <div class="footer-line"></div>
        
        <div class="footer-copyright">
            <p>&copy; 2024 Tunely</p>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'UsrAssets/js/playmusic.js ' %}"></script>
    <script src="{% static 'UsrAssets/js/playfromcover.js ' %}"></script>
    <script>
        function scrollToSection(sectionId) {
            var section = document.getElementById(sectionId);
            if (section) {
                section.scrollIntoView({ behavior: 'smooth' });
            }
        }
      </script>

</body>
</html>
{% endblock content %}